from django.conf import settings

MAX_LEN_NAME_TAG_ING_RECIPE_MEASUREMENT_UNIT = 200
MAX_LEN_COLOR_TAG = 16
MAX_LEN_EMAIL = 254
MAX_LEN_FIRST_LAST_NAME = 150
MAX_LEN_PASSWORD = 128

PATH_TO_FILE = f'{settings.BASE_DIR}/data/'
