version: '3.8'
services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: kalmmar4uk/foodgram_backend
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file: .env
    restart: always
    container_name: foodgram_backend

  frontend:
    env_file: .env
    image: kalmmar4uk/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    container_name: foodgram_frontend


  nginx:
    image: kalmmar4uk/foodgram_frontend
    ports:
      - "80:80"
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
    container_name: foodgram_nginx

volumes:
  postgres_data:
  static:
  media: